[config]
skip_core_tasks = true

# ---- BASIC ----

[tasks.watch]
description = "Watch files and recompile the project on change"
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = "-h" }
command = "trunk"
args = ["watch", "--open"]

[tasks.serve]
description = "Start server"
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = "-h" }
command = "trunk"
args = ["serve", "--open"]

# ---- BUILD ----

[tasks.build]
description = "Build with trunk"
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = "-h" }
command = "trunk"
args = ["build"]

[tasks.build_release]
description = "Build with trunk in release mode"
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = "-h" }
command = "trunk"
args = ["build", "--release"]

# ---- LINT ----

[tasks.clippy]
description = "Lint with Clippy"
install_crate = { rustup_component_name = "clippy", binary = "cargo-clippy", test_arg = "--help" }
command = "cargo"
args = ["clippy", "--all-features", "--", "--deny", "warnings", "--deny", "clippy::pedantic", "--deny", "clippy::nursery"]

[tasks.fmt]
description = "Format with rustfmt"
install_crate = { rustup_component_name = "rustfmt", binary = "rustfmt", test_arg = "-V" }
command = "cargo"
args = ["fmt"]
