// Generated By build.rs
pub const FILES: &[(&str, &str)] = &[
    ("2019-02-19-SonhosDoFuturoTec", include_str!(".././posts/2019-02-19-SonhosDoFuturoTec.md")),
    ("2019-02-12-Motivacionais", include_str!(".././posts/2019-02-12-Motivacionais.md")),
    ("2019-03-24-DotFiles", include_str!(".././posts/2019-03-24-DotFiles.md")),
    ("2019-02-12-Primeiro-teste", include_str!(".././posts/2019-02-12-Primeiro-teste.md")),
];
